### ISSUE TITLE
Fatal error if token is missing

### ISSUE THREAD

**Issue by mnwalker** [njoguamos/laravel-turnstile#12]
- Laravel Turnstile Version: 1.0.0
- Laravel Version: 9
- PHP Version: 8.0

### Description:
NjoguAmos\Turnstile\Http\Middleware\TurnstileMiddleware::validateTurnstile(): Argument #1 ($token) must be of type string, null given, called in /vendor/njoguamos/laravel-turnstile/src/Http/Middleware/TurnstileMiddleware.php on line 22

When spammers are submitting the form directly without any token, the app throws a fatal error.

The desired functionality would be treating a missing token as an invalid token without the fatal error.

This was data sent
--data 'g-recaptcha-response=&_token=wygYp8rwZNkUcJz5ejQa1CFz3zwcWgI1lrHaGccR&input_email=i8brd0@course-fitness.com&input_msg=冠天下娛樂城  
https://xn--ghq10gw1gvobv8a5z0d.com/&submit=&input_name=ShawnMef&_method=POST'

**Comment by njoguamos** [comment]
Thank you for raising this issue. Let me have a look.

**Comment by njoguamos** [comment]
Upgrade to [v1.0.1](https://github.com/njoguamos/laravel-turnstile/releases/tag/v1.0.1)
